import { data } from './data.js';
export function renderApp(h, state, actions) {
  const all=data.projects.filter(p=>p.category===state.category);
  const project=all.find(p=>p.id===state.project)||all[0];
  const step=project.steps[state.step]||project.steps[0];
  const el=(tag,props,...children)=>h(tag,props,...children.flat(Infinity).filter(v=>v!==null&&v!==undefined&&v!==false));
  const raw=(markup,props={})=>el('div',{...props,dangerouslySetInnerHTML:{__html:markup}});
  const link=(href,label,cls)=>el('a',{href,className:cls},label);
  const heading=(n,title,note)=>el('div',{className:'section-heading'},el('div',{},el('span',{className:'section-number'},n),el('h2',{},title)),note&&el('p',{},note));
  const keyboard=(event,ids,current,select)=>{let target=current;if(['ArrowRight','ArrowDown'].includes(event.key))target=(current+1)%ids.length;else if(['ArrowLeft','ArrowUp'].includes(event.key))target=(current-1+ids.length)%ids.length;else if(event.key==='Home')target=0;else if(event.key==='End')target=ids.length-1;else return;event.preventDefault();select(target);requestAnimationFrame(()=>document.getElementById(ids[target])?.focus());};
  return el('div',{},
    link('#main','跳到主要内容','skip'),
    el('div',{className:'hero-shell',id:'top'},
      el('header',{className:'site-nav container'},link('#top','SISI WANG','brand'),el('nav',{'aria-label':'主要导航'},link('#about','关于我'),link('#fit','岗位适配'),link('#portfolio','项目作品'),link('#contact','联系我'))),
      el('section',{className:'hero container','aria-label':'个人介绍'},el('div',{className:'hero-copy'},el('p',{className:'eyebrow'},'2027 CAMPUS RECRUITMENT · 华东师范大学'),el('h1',{},'用内容连接',el('span',{},'品牌与人'),el('br'), '让创意在现场发生。'),el('p',{className:'hero-english'},'Content · Communication · Execution'),el('p',{className:'hero-description'},'我是王镭澌。从音乐与舞台出发，',el('br'),'在内容创作、活动执行和多方协作中，把想法推进为真实的交付。'),el('div',{className:'hero-actions'},link('#contact','联系我 ↗','button accent'),el('a',{href:'assets/wang-leisi-resume.pdf',className:'button glass',target:'_blank',rel:'noopener'},'查看简历 ↗'))),el('div',{className:'hero-signature'},'王镭澌',el('span',{},'SISI WANG / PORTFOLIO')))),
    el('main',{id:'main'},
      el('section',{className:'about container section',id:'about'},el('div',{},el('p',{className:'eyebrow'},'01 / ABOUT ME'),el('h2',{},'音乐是起点，',el('br'),el('span',{className:'gradient-text'},'表达与协作是延伸。')),el('p',{className:'body-copy'},'我的实践横跨校园演出、文化活动、公众号内容与创作者沟通。音乐训练让我关注内容节奏和呈现，也习惯围绕明确的时间节点，与不同角色一起完成工作。'),el('div',{className:'about-tags'},['活动策划与执行','内容制作与传播','合作沟通'].map(t=>el('span',{key:t},t)))),el('div',{className:'education glass-panel',id:'education'},el('p',{className:'eyebrow'},'EDUCATION / 教育背景'),el('div',{className:'education-item'},el('time',{},'2023—2027'),el('h3',{},'华东师范大学'),el('p',{},'音乐表演本科 · 2027届'),el('p',{className:'muted'},'GPA专业前5% · 国家奖学金 · 一等奖学金')),el('div',{className:'education-item'},el('time',{},'2025.08—2025.12'),el('h3',{},'美国中阿肯色大学'),el('p',{},'公派交换 · 全英文学习与跨文化交流'),el('p',{className:'muted'},'面向100余名国际师生演奏中国传统音乐，积累跨语言专业沟通与文化内容呈现经验。')))),
      el('div',{className:'stats container'},[['10余场','参与校级文体活动'],['3,000余人','多场活动累计覆盖'],['84,792','代表视频观看数'],['30位','累计引入优质创作者']].map(([n,t])=>el('div',{key:n},el('strong',{},n),el('span',{},t)))),
      el('section',{className:'section container',id:'fit'},heading('02','我与岗位的适配度','从已经完成的工作，理解我的能力。'),el('div',{className:'fit-panel glass-panel'},el('div',{className:'assistant-header'},el('span',{className:'assistant-icon','aria-hidden':'true'},'S'),el('div',{},el('strong',{},'岗位适配分析'),el('p',{},'基于我的真实经历与作品整理'))),el('p',{className:'fit-lead'},'我的经验主要对应',el('strong',{},'活动策划与项目执行'),'，并延伸到',el('strong',{},'品牌活动传播、内容运营与合作沟通'),'。'),el('p',{className:'body-copy'},'音乐背景的价值，体现在具体工作中：把作品特点讲清楚，把信息组织成可阅读的内容，围绕演出节点完成准备，并在参与者提出问题时协调解决。'),el('div',{className:'skill-grid'},data.skills.map((s,i)=>el('article',{key:s.title},el('span',{className:'skill-index'},'0'+(i+1)),el('h3',{},s.title),el('p',{},s.body)))),el('div',{className:'fit-jumps'},link('#education','教育背景 ↗'),el('button',{onClick:()=>actions.jump('events')},'活动经历 ↗'),el('button',{onClick:()=>actions.jump('communication')},'对接能力 ↗'),el('button',{onClick:()=>actions.jump('content')},'内容运营 ↗')))),
      el('section',{className:'section portfolio container',id:'portfolio'},heading('03','项目与作品','选择类别与项目，查看从任务到交付的工作过程。'),
        el('div',{className:'category-tabs',role:'tablist','aria-label':'项目一级分类'},data.categories.map((c,i)=>el('button',{key:c.id,id:'category-'+c.id,role:'tab','aria-selected':state.category===c.id,'aria-controls':'category-panel',tabIndex:state.category===c.id?0:-1,onClick:()=>actions.category(c.id),onKeyDown:e=>keyboard(e,data.categories.map(x=>'category-'+x.id),i,n=>actions.category(data.categories[n].id))},c.label))),
        el('div',{id:'category-panel',role:'tabpanel','aria-labelledby':'category-'+state.category},
          el('div',{className:'project-tabs',role:'tablist','aria-label':'具体项目'},all.map((p,i)=>el('button',{key:p.id,id:'project-'+p.id,role:'tab','aria-selected':project.id===p.id,'aria-controls':'project-panel',tabIndex:project.id===p.id?0:-1,onClick:()=>actions.project(p.id),onKeyDown:e=>keyboard(e,all.map(x=>'project-'+x.id),i,n=>actions.project(all[n].id))},p.title))),
          el('article',{className:'project-card',id:'project-panel',role:'tabpanel','aria-labelledby':'project-'+project.id,key:project.id},
            el('div',{className:'project-title'},el('p',{className:'eyebrow'},'CASE STUDY / '+data.categories.find(c=>c.id===state.category).label),el('h3',{},project.title),el('p',{className:'project-meta'},project.meta)),el('p',{className:'project-summary'},project.summary),
            el('div',{className:'project-workflow'},el('aside',{className:'project-sidebar'},el('div',{className:'step-tabs',role:'tablist','aria-orientation':'vertical','aria-label':'项目工作流程'},project.steps.map((s,i)=>el('button',{key:project.id+'-'+i,id:'step-'+i,role:'tab','aria-selected':state.step===i,'aria-controls':'step-panel',tabIndex:state.step===i?0:-1,onClick:()=>actions.step(i),onKeyDown:e=>keyboard(e,project.steps.map((_,n)=>'step-'+n),i,actions.step)},el('span',{className:'step-dot','aria-hidden':'true'}),el('span',{className:'step-index'},String(i+1).padStart(2,'0')),s.label)))),el('div',{className:'step-panel',id:'step-panel',role:'tabpanel','aria-labelledby':'step-'+state.step,key:project.id+'-'+state.step,tabIndex:0},el('h4',{},String(state.step+1).padStart(2,'0')+' / '+step.title),raw(step.body,{className:'step-body'}),el('div',{className:'step-footer'},el('span',{},(state.step+1)+' / '+project.steps.length),el('div',{},el('button',{disabled:state.step===0,onClick:()=>actions.step(state.step-1),'aria-label':'上一步'},'← 上一步'),el('button',{disabled:state.step===project.steps.length-1,onClick:()=>actions.step(state.step+1),'aria-label':'下一步'},'下一步 →')))))))),
      el('section',{className:'moments section',id:'moments'},
        el('div',{className:'container moments-heading'},heading('04','工作照片墙','移动鼠标浏览 · 手机左右滑动 · 点击查看大图'),el('div',{className:'gallery-controls'},el('button',{onClick:()=>actions.galleryPage(-1),'aria-label':'向左浏览照片'},'←'),el('button',{onClick:()=>actions.galleryPage(1),'aria-label':'向右浏览照片'},'→'))),
        el('div',{className:'moments-track',id:'moments-track',tabIndex:0,role:'region','aria-label':'活动与工作照片长廊',onPointerMove:actions.galleryMove,onPointerLeave:actions.galleryStop,onFocus:actions.galleryStop,onKeyDown:actions.galleryKey},data.gallery.map((photo,i)=>el('figure',{className:'moment-card',key:photo.src},el('button',{onClick:()=>{actions.galleryStop();actions.photo(photo);},'aria-label':'放大查看：'+photo.caption},el('img',{src:photo.src,alt:photo.caption,loading:'lazy'}),el('span',{className:'moment-expand','aria-hidden':'true'},'↗')),el('figcaption',{},el('span',{},String(i+1).padStart(2,'0')),photo.caption)))))),
    el('section',{className:'contact-details container glass-panel',id:'contact','aria-labelledby':'contact-title'},el('div',{className:'contact-heading'},el('p',{className:'eyebrow'},'CONTACT'),el('h2',{id:'contact-title'},'联系我')),el('div',{className:'contact-options'},el('a',{href:'mailto:2528992757@qq.com',className:'contact-option'},el('span',{},'邮箱'),el('strong',{},'2528992757@qq.com'),el('i',{'aria-hidden':'true'},'↗')),el('a',{href:'tel:15356884515',className:'contact-option'},el('span',{},'电话'),el('strong',{},'15356884515'),el('i',{'aria-hidden':'true'},'↗')))),
    el('footer',{className:'container'},el('span',{},'© 王镭澌 · Sisi Wang'),link('#top','返回顶部 ↑')));
}
